services:
  - type: web
    name: ecom-admin-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend-domain.vercel.app
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /health 